version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cloud-cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cloud-cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cloud-cicd/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      # Debugging: Check the environment variables to ensure they are correctly set
      - echo "DOCKER_REGISTRY_USERNAME: $DOCKER_REGISTRY_USERNAME"
      - echo "DOCKER_REGISTRY_PASSWORD: $DOCKER_REGISTRY_PASSWORD"
      - echo "DOCKER_REGISTRY_URL: $DOCKER_REGISTRY_URL"
      
      # Ensure the Docker registry URL is correct (docker.io for Docker Hub)
      - export DOCKER_REGISTRY_URL=docker.io
      
      # Log in to Docker Hub using the credentials stored in the parameter store
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      
      # Check if Dockerfile is present in the current directory
      - ls -l
      
      # Build and tag the Docker image
      - docker build -t "$DOCKER_REGISTRY_USERNAME/sample-poc-repo:latest" .
      
      # Push the Docker image to Docker Hub
      - docker push "$DOCKER_REGISTRY_USERNAME/sample-poc-repo:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
